item {
    id: 1
    name: 'charizard'
}

item {
    id: 2
    name: 'gardevoir'
}

item {
    id: 3
    name: 'greninja'
}

item {
    id: 4
    name: 'mudkip'
}

item {
    id: 5
    name: pikachu
}
